"""
Django settings for Demo project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
from . import app, database, middleware, templates, auth, rest_framework, cache

sys.path.append('../vendor')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r1f+q+!s*dibi(um7#r(e)3k+c%lcyw8=ec9de29fils5&1*i0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = app.INSTALLED_APPS

MIDDLEWARE = middleware.MIDDLEWARE

ROOT_URLCONF = 'config.urls'

TEMPLATES = templates.TEMPLATES

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = database.DATABASES

CACHES = cache.CACHES

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = auth.AUTH_PASSWORD_VALIDATORS

AUTH_USER_MODEL = auth.AUTH_USER_MODEL

REST_FRAMEWORK = rest_framework.REST_FRAMEWORK

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

CORS_ORIGIN_ALLOW_ALL = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = templates.STATIC_URL

STATIC_ROOT = templates.STATIC_ROOT
